kind: pipline
name: Winsper-AdminService

steps:
  - name: test
    image: maven
    volumes:
      - name: dependency
        path: /root/.m2
    # - name: configuration
    #   path: /drone/src/back-end/src/main/resources/application.yml
    commands:
      - mvn clean
      - mvn package -Dmaven.test.skip=true
      - echo "test and package admin completed 🙂🙂🙂"

  - name: upload
    image: appleboy/drone-scp
    settings:
      host: 10.0.0.98
      username: root
      key:
        from_secret: private_key
      rm: true
      target: /root/test/Winsper/winsper-admin
      source:
        - target/admin-service-0.0.1-SNAPSHOT.jar
        - Dockerfile

  - name: deploy
    image: appleboy/drone-ssh
    settings:
      host: 10.0.0.98
      username: root
      key:
        from_secret: private_key
      script:
        - cd /root/test/Winsper/winsper-admin/target
        - cp ../Dockerfile .
        - docker rm -f deeell-test/winsper-admin
        - docker build -t deeell-test/winsper-admin .
        - docker login
        - docker push deeell-test/winsper-admin


volumes:
  - name: dependency
    host:
      path: /root/.m2
