kind: pipline
name: Winsper-AdminService

steps:
- name: test
  image: maven
  volumes:
  - name: dependency
    path: /root/.m2
# - name: configuration
#   path: /drone/src/back-end/src/main/resources/application.yml
  commands:
  - mvn clean
  - mvn package
  - echo "test and package admin-service completed 🙂🙂🙂"

- name: upload
  image: appleboy/drone-scp
  settings:
    host: 101.132.176.33
    username: root
    password:
      from_secret: xyx_password
    rm: true
    target: /Winsper/admin-service
    source:
    - target/admin-service.jar
    - Dockerfile

- name: deploy
  image: appleboy/drone-ssh
  settings:
    host: 101.132.176.33
    username: root
    password:
      from_secret: xyx_password
    script:
    - cd /Winsper/admin-service/target
    - cp ../Dockerfile .
    - docker build -t winsper-admin-service .
    - docker rm -f winsper-admin-service-c
    - docker run -d --name winsper-admin-service-c -p 7170:7170 winsper-admin-service

volumes:
- name: dependency
  host:
    path: /root/.m2